name: Shaken
version: 1.0
main: eu.treppi.playlegends.shaken.ShakenPlugin
author: treppi
api-version: "1.20"

commands:
  shaken:
    description: shaken command
  permcheck:
    description: test command